
package osi_layer;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

public class osilayer extends javax.swing.JFrame {
 StringBuffer sb=new StringBuffer();
    String msg,input_msg;
    int len,inp_msg_len,c=0,c1=0,c2=0,c3=0,c4=0,c5=0,c6=0;
    ArrayList<String> al=new ArrayList<>();
    public osilayer() {
        initComponents();
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txt2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txt3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txt4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        txt5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        txt6 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        txt8 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        txt7 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start Process");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt1.setText("jTextField2");

        jButton2.setText("Application Layer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt2.setText("jTextField3");

        jButton3.setText("Presentation Layer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txt3.setText("jTextField4");

        jButton4.setText("Session Layer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txt4.setText("jTextField5");

        jButton5.setText("Transport Layer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txt5.setText("jTextField6");

        jButton6.setText("Network Layer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txt6.setText("jTextField7");

        jButton7.setText("Physical Layer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txt8.setText("jTextField8");

        jButton8.setText("Data Link Layer");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        txt7.setText("jTextField9");
        txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(txt3)
            .addComponent(txt4)
            .addComponent(txt5)
            .addComponent(txt6)
            .addComponent(txt8)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jButton8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton7)))
                .addContainerGap(332, Short.MAX_VALUE))
            .addComponent(txt7)
            .addComponent(txt1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(3, 3, 3)
                .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    
        
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      // TODO add your handling code here:
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         

       // TODO add your handling code here:
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//new Thread is started
      seven_layer_protocol slp=new seven_layer_protocol();//calling the constructor...
       slp.start();//start the new thread
 
                 
        // TODO add your handling code here:
    }                                        

    private void txt7ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      // TODO add your handling code here:
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(osilayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(osilayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(osilayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(osilayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new osilayer().setVisible(true);
            }
        });
    }
   class seven_layer_protocol extends Thread{
    StringBuffer sb=new StringBuffer();
    String msg,input_msg,message;
    int len,len2;
    Scanner sc=new Scanner(System.in);
    ArrayList<Integer> al=new ArrayList<>();
    
    public void run()
    {
        try {
            //the main function is called...where the input message is given
            application_layer_msg();
     }
        //exception handling
        catch (IOException ex) {
            Logger.getLogger(seven_layer_protocol.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(seven_layer_protocol.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    //application layer 
    public void application_layer(String message,int len2) throws InterruptedException{
        String msg1="Application_layer_header;";
        String msg2=message;
        String msg_app=msg1+msg2;
        int len1=msg1.length();
        len=len1+len2;
        //adding the header and length...
         msg=add_header(msg_app,len);
         Thread.sleep(1000);//Thread sleep for 1000ms
        txt2.setText(msg+"");
         txt1.setText("");
         //presentation layer...
       presentation_layer(msg,len);
        
    }
    public void presentation_layer(String msg,int len2) throws InterruptedException
    {
        String msg_pre="Presentation_Layer_header;";
        //adding the header and length...
        msg=add_header(msg_pre,len);
         Thread.sleep(1000);//Thread sleep for 1000ms
         txt3.setText(msg+"");
           txt2.setText("");
           //call the session layer...
        session_layer(msg,len);
                
                
    }
    //Session Layer
    public void session_layer(String msg,int len2) throws InterruptedException{
     String msg_pre="Session_Layer_header;";
     //adding the header and length...
        msg=add_header(msg_pre,len);
      Thread.sleep(1000);//Thread sleep for 1000ms
         txt4.setText(msg+"");
           txt3.setText("");
           //call the Transport layer...
        transport_layer(msg,len);
        
    }
    //Transport Layer
    public void transport_layer(String msg,int len2) throws InterruptedException{
        String msg_pre="Transport_Layer_header;";
        //adding the header and length...
        msg=add_header(msg_pre,len);
        Thread.sleep(1000);//Thread sleep for 1000ms
         txt5.setText(msg+"");
          txt4.setText("");
          //call the network layer...
        network_layer(msg,len);
    }
    //Network Layer
     public void network_layer(String msg,int len2) throws InterruptedException{
        String msg_pre="Network_Layer_header;";
        //adding the header and length...
        msg=add_header(msg_pre,len);
         Thread.sleep(1000); //Thread sleep for 1000ms
        txt6.setText(msg+"");
        txt5.setText("");
        //call the data link layer...
        datalink_layer(msg,len);
    }
     //Data Link Layer
      public void datalink_layer(String msg,int len2) throws InterruptedException{
        String msg_pre="DataLink_Layer_header;";
        msg=add_header(msg_pre,len);
         Thread.sleep(1000);//Thread sleep for 1000ms
         txt7.setText(msg+"");
          txt6.setText("");
          //call the physical layer...
        physical_layer(msg,len);
    }
      //physical Layer
       public void physical_layer(String msg,int len2) throws InterruptedException{
        String msg_pre="Physical_Layer_header;";
        //adding the header and length...
        msg=add_header(msg_pre,len);
         Thread.sleep(1000);//Thread sleep for 1000ms
        txt8.setText(msg+"");
         txt7.setText("");
       
    }
       public void application_layer_msg() throws IOException, InterruptedException
       {//clearing the text...
           txt1.setText("");
           txt2.setText("");
           txt3.setText("");
           txt4.setText("");
           txt5.setText("");
           txt6.setText("");
           txt7.setText("");
           txt8.setText("");
           
           //message to be send
         input_msg="Hello";
           int inp_msg_len=input_msg.length();//length of message
           txt1.setText(input_msg+"");
           //call the application layer...
          application_layer(input_msg,inp_msg_len);
           
       }
       //appending  the header at each layer...
       public String add_header(String msg,int len)
       {int sum=0;
           int length=msg.length();
          al.add(length);
          for(int i=0;i<al.size();i++)
          {
              sum=sum+al.get(i);//total length of the message
          }
          // System.out.println(" "+sum);
           sb.insert(0, msg);//appending the header in string buffer
          return sb.toString();
       }
       
     
            
}


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    // End of variables declaration                   
}
